### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by arnoutaertgeerts** [Syonet/model#9]
I tried understanding all the capabilities of the module by quickly looking to the code but missed these things:

- Where do you specify to which couchdb instance you want to sync?
- Can this be used with any backend? For example a Mongo backend?

Could it be possible to update the documentation about the remote a little bit? I also think some full working examples could be useful :)

I'm willing to help so let me know what your plans for this module are!

**Comment by gustavohenke** [comment]
Hello @arnoutaertgeerts,
I agree with you, this project needs lots of documentation.

For now, the backend must be a RESTful API. Everytime you invoke one of `.list()`, `.get()`, `.save()`, `.patch()` or `.remove()`, an HTTP request will be made.

When you are offline or the target server is offline, this what will happen:
* `.list()` and `.get()` will return the values cached in PouchDB;
* `.post()`, `.patch()` and `.remove()` will have their requests stored for trying again later.

The only plan I have so far is to allow streaming the cached values right away (see #8), so the user doesn't need to wait until the request fails because no connection could be made.

**Comment by arnoutaertgeerts** [comment]
@gustavohenke I went through the code more rigorously now and think you are taking a nice approach. However, I still have some questions:

- If the server and client are online, do the requests get saved locally? Or does this only happen when you are offline. For example, when I'm online and call `.list()` to fetch a collection of 10 documents of which I already have 9, how will the request handle this? Or, if I'm online and have no stored documents while calling `.list()`. Will these documents get saved to the local database?

- I like the fact you let angular do the requests instead of pouchDB but I'm a bit worried it might be difficult to implement the `.sync()`functionality this way. Now, as I understand, `.sync()` means retry the requests that you made while being offline. This does not automatically update a collection when this collection is changed on a different client, or am I wrong? (i.e. There is no `push` behavior).

**Comment by gustavohenke** [comment]
Hello @arnoutaertgeerts, thanks for your interest in this project!
There are news going on. Take a look at #10, or the branch `v2.x`.

> If the server and client are online, do the requests get saved locally? Or does this only happen when you are offline.

Always. Methods that modify data will modify the cache like they're supposed to do, methods that return data will update the cache like they're supposed to do.

> when I'm online and call .list() to fetch a collection of 10 documents of which I already have 9, how will the request handle this?

It will replace the existing documents and insert the new ones. Let me explain how we do this:
If your RESTful API always returns `id` as the identifier of your data, then you don't have to do anything else. This key will be used in every object to link server data with PouchDB data.

But, if your RESTful API returns varying ID fields for different endpoints (like our API at Syonet does), then we'll guess the ID based in some header which contains the ID fields, for example:

```javascript
model( "user" ).list();
```

```http
GET /user HTTP/1.1
Content-Type: application/json
X-Id-Field: userId


[{
  "userId": 1,
  ...
}]
```

In this hypothetical situation, a PouchDB instance would be created with the name `user` storing object by their `userId` field. `X-Id-Field` [is the default value](/Syonet/model/blob/27aff8a9c71a6a3237d817b85e92ab1c232cc88a/src/model.js#L17) for such header.

I'll include a section about this behavior before cutting another release.

> I like the fact you let angular do the requests instead of pouchDB but I'm a bit worried it might be difficult to implement the .sync() functionality this way

It would be difficult anyway for us. We use relational DBs, with various levels of nested resources.
We needed some way to make sure requests respect their dependencies, replacing references in other requests (this is a problem I came across recently, so it's another feature expected for version 2.x). PouchDB/CouchDB doesn't have this problem, so it's way easier to implement synchronization.

> This does not automatically update a collection when this collection is changed on a different client, or am I wrong?

You're right. Model has no conflict detection yet. Feel free to suggest some way to implement it.

**Comment by gustavohenke** [comment]
@arnoutaertgeerts Do you have any further questions about the documentation?
I made lots of updates since v2.0.0, but how the synchronization works is a main thing that's missing (for this I created #15).

**Comment by gustavohenke** [comment]
I'm closing, but feel free to let me know of any questions you may have!
